import { jsPDF } from 'jspdf'
import { formatIls } from '@/lib/tax/decimal'
import type { TaxResult } from '@/lib/tax/types'

export function generatePdf(result: TaxResult, taxYear: number): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  let y = 20

  const line = (text: string, size = 10, bold = false) => {
    doc.setFontSize(size)
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.text(text, 15, y)
    y += size * 0.5 + 2
  }
  const gap = (n = 4) => { y += n }
  const rule = () => { doc.setDrawColor(200); doc.line(15, y, pageW - 15, y); y += 4 }
  const right = (label: string, value: string) => {
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text(label, 15, y)
    doc.setFont('helvetica', 'bold')
    doc.text(value, pageW - 15, y, { align: 'right' })
    y += 6
  }

  line(`IB-Taxil — Israeli Tax Report`, 16, true)
  line(`Tax Year: ${taxYear}`, 12)
  gap()
  rule()

  line('TAX SUMMARY', 11, true)
  gap(2)
  right('Net Capital Gain', formatIls(result.netCapitalGainIls))
  right('Capital Gains Tax (25%)', formatIls(result.capitalGainsTaxIls))
  right('Total Dividends', formatIls(result.totalDividendsIls))
  right('Dividends Tax', formatIls(result.dividendsTaxIls))
  right('Foreign Tax Credits Applied', `-${formatIls(result.totalForeignTaxCreditIls)}`)
  gap()
  doc.setDrawColor(59, 130, 246)
  doc.line(15, y, pageW - 15, y)
  y += 4
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('ESTIMATED TAX LIABILITY', 15, y)
  doc.text(formatIls(result.totalTaxLiabilityIls), pageW - 15, y, { align: 'right' })
  y += 10

  rule()
  line('CAPITAL GAINS DETAIL', 11, true)
  gap(2)
  for (const l of result.capitalGainLines) {
    if (y > 260) { doc.addPage(); y = 20 }
    right(`${l.ticker} (${l.saleDateStr})`, formatIls(l.gainLossIls))
  }

  gap()
  rule()
  line('DIVIDENDS DETAIL', 11, true)
  gap(2)
  for (const l of result.dividendLines) {
    if (y > 260) { doc.addPage(); y = 20 }
    right(`${l.ticker} (${l.date}) — net due`, formatIls(l.netTaxDue))
  }

  gap(6)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'italic')
  doc.setTextColor(150)
  doc.text(
    'This report is a calculation aid generated by IB-Taxil. It is not legal or tax advice. Verify with a licensed Israeli tax advisor before filing.',
    15, y, { maxWidth: pageW - 30 }
  )

  doc.save(`IB-Taxil-${taxYear}.pdf`)
}
